from players import PLAYERS

@dp.message(Command("players"))
async def players_command(message: Message):
    text = "⚽ Игроки:\n\n"

    for i, player in enumerate(PLAYERS, 1):
        text += f"{i}. {player['name']} — {player['rating']} OVR\n"

    await message.answer(text)



PLAYERS = [
    {"name": "Ламин Ямаль", "nation": "Испания", "rating": 89},
    {"name": "Рафинья", "nation": "Бразилия", "rating": 90},
    {"name": "Педри", "nation": "Испания", "rating": 88},
    {"name": "Гави", "nation": "Испания", "rating": 83},
    {"name": "Дани Ольмо", "nation": "Испания", "rating": 86},
    {"name": "Жюль Кунде", "nation": "Франция", "rating": 85},
    {"name": "Лионель Месси", "nation": "Аргентина", "rating": 86},
    {"name": "Луис Суарес", "nation": "Уругвай", "rating": 82},
    {"name": "Родриго Де Пауль", "nation": "Аргентина", "rating": 83},
    {"name": "Серхио Регилон", "nation": "Испания", "rating": 77},
    {"name": "Тадео Альенде", "nation": "Аргентина", "rating": 75},
    {"name": "Тьяско Сеговия", "nation": "Венесуэла", "rating": 73},
    {"name": "Гарри Кейн", "nation": "Англия", "rating": 90},
    {"name": "Джамал Мусиала", "nation": "Германия", "rating": 88},
    {"name": "Майкл Олисе", "nation": "Франция", "rating": 85},
    {"name": "Йозуа Киммих", "nation": "Германия", "rating": 89},
    {"name": "Мануэль Нойер", "nation": "Германия", "rating": 85},
    {"name": "Луис Диас", "nation": "Колумбия", "rating": 86},
    {"name": "Усман Дембеле", "nation": "Франция", "rating": 91},
    {"name": "Хвича Кварацхелия", "nation": "Грузия", "rating": 87},
    {"name": "Ашраф Хакими", "nation": "Марокко", "rating": 89},
    {"name": "Витинья", "nation": "Португалия", "rating": 89},
    {"name": "Жоау Невеш", "nation": "Португалия", "rating": 86},
    {"name": "Маркиньос", "nation": "Бразилия", "rating": 87},
    {"name": "Килиан Мбаппе", "nation": "Франция", "rating": 91},
    {"name": "Джуд Беллингем", "nation": "Англия", "rating": 90},
    {"name": "Винисиус Жуниор", "nation": "Бразилия", "rating": 90},
    {"name": "Арда Гюлер", "nation": "Турция", "rating": 81},
    {"name": "Трент Александер-Арнольд", "nation": "Англия", "rating": 86},
    {"name": "Антонио Рюдигер", "nation": "Германия", "rating": 85},
    {"name": "Коул Палмер", "nation": "Англия", "rating": 88},
    {"name": "Жоау Педро", "nation": "Бразилия", "rating": 82},
    {"name": "Мойсес Кайседо", "nation": "Эквадор", "rating": 84},
    {"name": "Энцо Фернандес", "nation": "Аргентина", "rating": 84},
    {"name": "Уэсли Фофана", "nation": "Франция", "rating": 78},
    {"name": "Николас Джексон", "nation": "Сенегал", "rating": 80},
    {"name": "Бруну Фернандеш", "nation": "Португалия", "rating": 87},
    {"name": "Матеус Кунья", "nation": "Бразилия", "rating": 84},
    {"name": "Лисандро Мартинес", "nation": "Аргентина", "rating": 85},
    {"name": "Матиас Де Лигт", "nation": "Нидерланды", "rating": 84},
    {"name": "Амад Диалло", "nation": "Кот-д’Ивуар", "rating": 78},
    {"name": "Расмус Хёйлунн", "nation": "Дания", "rating": 78},
    {"name": "Эрлинг Холанд", "nation": "Норвегия", "rating": 91},
    {"name": "Фил Фоден", "nation": "Англия", "rating": 88},
    {"name": "Бернарду Силва", "nation": "Португалия", "rating": 88},
    {"name": "Жереми Доку", "nation": "Бельгия", "rating": 84},
    {"name": "Савиньо", "nation": "Бразилия", "rating": 82},
    {"name": "Йошко Гвардиол", "nation": "Хорватия", "rating": 85},
    {"name": "Букайо Сака", "nation": "Англия", "rating": 87},
    {"name": "Деклан Райс", "nation": "Англия", "rating": 87},
    {"name": "Мартин Эдегор", "nation": "Норвегия", "rating": 87},
    {"name": "Уильям Салиба", "nation": "Франция", "rating": 87},
    {"name": "Габриэл Магальяйнс", "nation": "Бразилия", "rating": 85},
    {"name": "Кай Хаверц", "nation": "Германия", "rating": 83},
    {"name": "Рафаэл Леау", "nation": "Португалия", "rating": 86},
    {"name": "Кристиан Пулишич", "nation": "США", "rating": 84},
    {"name": "Лука Модрич", "nation": "Хорватия", "rating": 82},
    {"name": "Майк Меньян", "nation": "Франция", "rating": 87},
    {"name": "Фикайо Томори", "nation": "Англия", "rating": 80},
    {"name": "Сантьяго Хименес", "nation": "Мексика", "rating": 81},
    {"name": "Флориан Вирц", "nation": "Германия", "rating": 89},
    {"name": "Вирджил ван Дейк", "nation": "Нидерланды", "rating": 88},
    {"name": "Алексис Макаллистер", "nation": "Аргентина", "rating": 86},
    {"name": "Доминик Собослаи", "nation": "Венгрия", "rating": 82},
    {"name": "Райан Гравенберх", "nation": "Нидерланды", "rating": 81},
    {"name": "Конор Брэдли", "nation": "Северная Ирландия", "rating": 75},
    {"name": "Кенан Йылдыз", "nation": "Турция", "rating": 78},
    {"name": "Душан Влахович", "nation": "Сербия", "rating": 83},
    {"name": "Тён Копмейнерс", "nation": "Нидерланды", "rating": 81},
    {"name": "Мануэль Локателли", "nation": "Италия", "rating": 82},
    {"name": "Бремер", "nation": "Бразилия", "rating": 86},
    {"name": "Андреа Камбьязо", "nation": "Италия", "rating": 81},
    {"name": "Хулиан Альварес", "nation": "Аргентина", "rating": 88},
    {"name": "Антуан Гризманн", "nation": "Франция", "rating": 87},
    {"name": "Пабло Барриос", "nation": "Испания", "rating": 78},
    {"name": "Коке", "nation": "Испания", "rating": 82},
    {"name": "Маркос Льоренте", "nation": "Испания", "rating": 84},
    {"name": "Ян Облак", "nation": "Словения", "rating": 88},
    {"name": "Криштиану Роналду", "nation": "Португалия", "rating": 84},
    {"name": "Жоау Феликс", "nation": "Португалия", "rating": 80},
    {"name": "Садио Мане", "nation": "Сенегал", "rating": 84},
    {"name": "Марсело Брозович", "nation": "Хорватия", "rating": 81},
    {"name": "Аймерик Ляпорт", "nation": "Испания", "rating": 84},
    {"name": "Бенто", "nation": "Бразилия", "rating": 81},
    {"name": "Эмилиано Мартинес", "nation": "Аргентина", "rating": 86},
    {"name": "Морган Роджерс", "nation": "Англия", "rating": 82},
    {"name": "Олли Уоткинс", "nation": "Англия", "rating": 84},
    {"name": "Юри Тилеманс", "nation": "Бельгия", "rating": 81},
    {"name": "Пау Торрес", "nation": "Испания", "rating": 82},
    {"name": "Матео Руджери", "nation": "Италия", "rating": 78},
    {"name": "Джеймс Мэддисон", "nation": "Англия", "rating": 83},
    {"name": "Дестини Удоджи", "nation": "Италия", "rating": 81},
    {"name": "Кристиан Ромеро", "nation": "Аргентина", "rating": 86},
    {"name": "Ришарлисон", "nation": "Бразилия", "rating": 80},
    {"name": "Мики Мур", "nation": "Англия", "rating": 70},
    {"name": "Гульельмо Викарио", "nation": "Италия", "rating": 84},
    {"name": "Райан Голд", "nation": "Новая Зеландия", "rating": 72},
    {"name": "Педро Вите", "nation": "Эквадор", "rating": 70},
    {"name": "Самуэль Адекугбе", "nation": "Канада", "rating": 68},
    {"name": "Тристан Блэкууд", "nation": "Новая Зеландия", "rating": 65},
    {"name": "Брайан Уайт", "nation": "США", "rating": 76},
    {"name": "Йоэйль", "nation": "Испания", "rating": 75},
    {"name": "Скотт Мактоминей", "nation": "Шотландия", "rating": 82},
    {"name": "Кевин Де Брёйне", "nation": "Бельгия", "rating": 86},
    {"name": "Ромелу Лукаку", "nation": "Бельгия", "rating": 84},
    {"name": "Маттео Политано", "nation": "Италия", "rating": 80},
    {"name": "Джованни Ди Лоренцо", "nation": "Италия", "rating": 82},
    {"name": "Алекс Мерет", "nation": "Италия", "rating": 82},
    {"name": "Пауло Дибала", "nation": "Аргентина", "rating": 84},
    {"name": "Лоренцо Пеллегрини", "nation": "Италия", "rating": 82},
    {"name": "Джанлука Манчини", "nation": "Италия", "rating": 81},
    {"name": "Артём Дзюба", "nation": "Россия", "rating": 72},
    {"name": "Анхелиньо", "nation": "Испания", "rating": 80},
    {"name": "Миле Свилар", "nation": "Сербия", "rating": 80},
    {"name": "Роберт Левандовски", "nation": "Польша", "rating": 88},
    {"name": "Дарвин Нуньес", "nation": "Уругвай", "rating": 82},
    {"name": "Сергей Милинкович-Савич", "nation": "Сербия", "rating": 84},
    {"name": "Рубен Невеш", "nation": "Португалия", "rating": 82},
    {"name": "Жоау Канселу", "nation": "Португалия", "rating": 84},
    {"name": "Калиду Кулибали", "nation": "Сенегал", "rating": 82},
]
